### PR TITLE
Add Fedora Package Installation

### PR DESCRIPTION
**Pull request by bexelbie**

### CODE REVIEW

**Comment by bexelbie** [comment]
The package is not available in CentOS.  Please retest with Fedora.

**Comment by bexelbie** [comment]
To get it into CentOS, we would need to land it in EPEL.  That is a 10 year update responsibility.  I am not opposed to it, but it'd be nice to know if we expect releases to result in a new major version number anytime soon.  IIRC, there is a rule about those in EPEL.

**Comment by awdeorio** [comment]
> The package is not available in CentOS. Please retest with Fedora.

Retesting with Fedora works
```console
$ vagrant init fedora/30-cloud-base 
$ vagrant up
$ vagrant ssh
[vagrant@localhost ~]$ sudo dnf install python3-mailmerge
...
[vagrant@localhost ~]$ which mailmerge
/usr/bin/mailmerge
[vagrant@localhost ~]$ mailmerge --version
mailmerge, version 1.9
```

> To get it into CentOS, we would need to land it in EPEL. That is a 10 year update responsibility. I am not opposed to it, but it'd be nice to know if we expect releases to result in a new major version number anytime soon. IIRC, there is a rule about those in EPEL.

I don't have plans for major changes to mailmerge, just a few minor enhancements list in the issues https://github.com/awdeorio/mailmerge/issues  It would be nice for users to be able to easily install the package!

**Comment by bexelbie** [comment]
These changes look fine.  Do you need me to squash them?  I don't seem to be able to approve a review.

**Comment by awdeorio** [comment]
LGTM!

**Pull request merged**
